export const ADD_NEW_PRODUCT = 'ADD_NEW_PRODUCT';
export const REMOVE_NEW_PRODUCT = 'REMOVE_NEW_PRODUCT';

export const SHOW_INFO_MESSAGE = 'SHOW_INFO_MESSAGE';
export const SHOW_ERROR_MESSAGE = 'SHOW_ERROR_MESSAGE';
export const SHOW_WARN_MESSAGE = 'SHOW_WARN_MESSAGE';

export const LOADING_DATA = 'LOADING_DATA';
