export const LOAD_BASE_PRODUCTS = 'LOAD_BASE_PRODUCTS';
export const API_LOAD_BASE_PRODUCTS = 'API_LOAD_BASE_PRODUCTS';

export const ADD_NEW_PRODUCT = 'ADD_NEW_PRODUCT';
export const REMOVE_NEW_PRODUCT = 'REMOVE_NEW_PRODUCT';

export const SHOW_INFO_MESSAGE = 'SHOW_INFO_MESSAGE';
export const SHOW_ERROR_MESSAGE = 'SHOW_ERROR_MESSAGE';
export const SHOW_WARN_MESSAGE = 'SHOW_WARN_MESSAGE';

export const LOADING_DATA = 'LOADING_DATA';

export const CHANGE_ROUTE = 'CHANGE_ROUTE';

export const LOGIN_USER_REQUEST = 'LOGIN_USER_REQUEST';
export const LOGIN_USER_RESPONSE = 'LOGIN_USER_RESPONSE';
export const LOGOUT_USER = 'LOGOUT_USER';
export const API_LOGIN_USER = 'API_LOGIN_USER';
